// /////////////////////////////////////////////////////////////////////////////////////////////////
// Generated by Layouts.dev
// ------------------------------------------------------------------------------------------------
// Copyright Creative Robots Inc. 2025 - All rights reserved
// https://layouts.dev
// ------------------------------------------------------------------------------------------------
// We are constantly improving the way this code is generated.
// Notice something wrong? Please let us know at hey@creative-robots.ai and we'll fix it!
// /////////////////////////////////////////////////////////////////////////////////////////////////

// ------------------------------------------------------------------------------------------------
// Project setup instructions
// ------------------------------------------------------------------------------------------------
// npm install --save @layouts.dev/utils
// npm install --save react
// npx shadcn-ui@latest init
// npx shadcn-ui@latest add button
// npx shadcn@latest add calendar
// npx shadcn@latest add input
// npx shadcn@latest add label
// npx shadcn@latest add textarea
// ------------------------------------------------------------------------------------------------

import React from 'react';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
//import { InlineSvg } from '@layouts.dev/utils';
import { CalendarIcon, KeyboardMusicIcon, NotebookIcon, TimerIcon } from 'lucide-react';
import { Fragment } from 'react';

export default function App() {
	return (
	    <div className="flex flex-col size-full min-h-screen items-start justify-start" >
	        <Fragment>
	            <div className="absolute size-full z-0" >
	                {/* Background pattern by @ibelick (https://bg.ibelick.com/) */}
	                <div className="absolute top-0 z-[-2] w-screen h-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]" />
	            </div>
	            <div className="relative size-full z-1 dark" >
	                <div className="flex items-center justify-center min-h-screen" >
	                    <Label className="relative items-center cursor-pointer bg-white/[.05] size-fit gap-px overflow-visible flex-col flex rounded-[35px] p-2 pl-6 pr-6 border-t border-accent-200/50 transition-all duration-700" >
	                        <Input className="sr-only peer" type="checkbox" />
	                        <div className="items-center justify-start flex opacity-100 h-12 w-fit peer-checked:opacity-0 peer-checked:w-0 peer-checked:translate-y-5 peer-checked:sr-only transition-all ease-in-out duration-300" >
	                            Let&#x27;s start
	                        </div>
	                        <div className="items-center justify-start flex opacity-0 scale-50 blur-md w-0 sr-only peer-checked:not-sr-only peer-checked:blur-none peer-checked:opacity-100 peer-checked:w-fit peer-checked:scale-100 transition-all ease-out duration-300" >
	                            <div className="size-fit p-2.5 rounded-2xl relative hover:bg-white/10 group" >
	                                <CalendarIcon className="size-6 text-white opacity-75" />
	                                <Calendar className="bg-white/10 rounded-lg p-2 absolute w-fit bottom-5 left-1/2 -translate-x-1/2 blur-md z-10 opacity-0 scale-50 group-hover:opacity-100 group-hover:scale-100 group-hover:bottom-16 group-hover:blur-none group-hover:z-20 transition-all ease-in-out duration-300 delay-100" key="line_41" />
	                            </div>
	                            <div className="size-fit p-2.5 rounded-2xl hover:bg-white/10 group group" >
	                                <TimerIcon className="size-6 text-white opacity-75" />
	                                <div className="bg-white/10 rounded-lg p-2 absolute w-fit bottom-5 left-1/2 -translate-x-[100px] blur-md z-10 opacity-0 scale-50 group-hover:opacity-100 group-hover:scale-100 group-hover:bottom-16 group-hover:blur-none group-hover:z-20 transition-all ease-in-out duration-300 delay-100" >
	                                    <div className="w-full justify-start items-center flex-col flex gap-2.5 pr-2 pl-2" >
	                                        <h3 className="text-semibold text-xl" >
	                                            Timer
	                                        </h3>
	                                        <h1 className="text-semibold text-3xl" >
	                                            12:00
	                                        </h1>
	                                        <Button className="gap-2 bg-white/20 text-white hover:bg-white/50 active:bg-white/70" variant="default" >
	                                            Start timer
	                                        </Button>
	                                    </div>
	                                </div>
	                            </div>
	                            <div className="size-fit p-2.5 rounded-2xl hover:bg-white/10 group" >
	                                <NotebookIcon className="size-6 text-white opacity-75"  />
                                    {/* src="https://illustrations.dev/lucide%3Anotebook-pen"*/}
	                                <div className="bg-white/10 rounded-lg p-2 absolute w-fit bottom-5 left-1/2 -translate-x-[90px] blur-md z-10 opacity-0 scale-50 group-hover:opacity-100 group-hover:scale-100 group-hover:bottom-16 group-hover:blur-none group-hover:z-20 transition-all ease-in-out duration-300 delay-100" >
	                                    <div className="justify-start items-start flex-col flex gap-2.5 pr-2 pl-2 w-[200px]" >
	                                        <h3 className="text-semibold text-xl w-fit" >
	                                            Quick notes
	                                        </h3>
	                                        <Textarea className="bg-white/30 backdrop-blur-sm" />
	                                    </div>
	                                </div>
	                            </div>
	                            <div className="size-fit p-2.5 rounded-2xl hover:bg-white/10 group" >
	                                <KeyboardMusicIcon className="size-6 text-white opacity-75" />
	                                <div className="bg-white/10 rounded-lg p-2 absolute w-fit bottom-5 left-1/2 -translate-x-[90px] blur-md z-10 opacity-0 scale-50 group-hover:opacity-100 group-hover:scale-100 group-hover:bottom-16 group-hover:blur-none group-hover:z-20 transition-all ease-in-out duration-300 delay-100" >
	                                    <div className="justify-start items-start flex-col flex gap-2.5 pr-2 pl-2 w-fit" >
	                                        <div className="w-full items-center justify-start flex h-[150px] gap-3 absolute bottom-11 left-1/2 -translate-x-[96px] z-10" >
	                                            <div className="w-[40px] h-[80px] bg-[#1A1A1A] rounded-br-lg rounded-bl-lg border-b hover:bg-[#292929] transition-opacity duration-200" />
	                                            <div className="w-[40px] h-[80px] bg-[#1A1A1A] rounded-br-lg rounded-bl-lg border-b hover:bg-[#292929] transition-opacity duration-200" />
	                                            <div className="w-[40px] h-[80px] bg-[#1A1A1A] rounded-br-lg rounded-bl-lg border-b hover:bg-[#292929] transition-opacity duration-200" />
	                                            <div className="w-[40px] h-[80px] bg-[#1A1A1A] rounded-br-lg rounded-bl-lg border-b hover:bg-[#292929] transition-opacity duration-200" />
	                                        </div>
	                                        <div className="w-full items-center justify-start flex h-[150px] gap-0.5" >
	                                            <div className="w-[50px] h-full bg-white/70 rounded-md hover:bg-white/90 transition-opacity duration-200" />
	                                            <div className="w-[50px] h-full bg-white/70 rounded-md hover:bg-white/90 transition-opacity duration-200" />
	                                            <div className="w-[50px] h-full bg-white/70 rounded-md hover:bg-white/90 transition-opacity duration-200" />
	                                            <div className="w-[50px] h-full bg-white/70 rounded-md hover:bg-white/90 transition-opacity duration-200" />
	                                            <div className="w-[50px] h-full bg-white/70 rounded-md hover:bg-white/90 transition-opacity duration-200" />
	                                        </div>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                    </Label>
	                </div>
	            </div>
	        </Fragment>
	    </div>
	);
}